version: '3.8'
services:
  nginx:
    ports:
      - '5000:80'
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=shonjoy
      - MONGO_PASSWORD=rsshonjoy
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shonjoy
      - MONGO_INITDB_ROOT_PASSWORD=rsshonjoy
